site_name: Ycash&trade; Foundation

theme:
  name: 'material'
  logo: 'ycash001.png'
  favicon: 'ycash001.png'
  palette:
    primary: 'Blue Grey'
    accent: 'Amber'

nav:
  - Home: index.md
  - Download: download.md
  - About: about.md
  - Exchanges: exchanges.md
  - Explorers: explorers.md
  - Get Involved: get_involved.md
  #- Mining: mining.md
  - Blog: blog.md
  - The Fork: the_fork.md
  - Documentation:
    - ycashd and YecWallet: docs/yecwallet_and_ycashd.md
    - Diversified Addresses: docs/diversified_addresses.md
    - Importing Private Keys: docs/privkey_import.md
    - Nullifier Migration: docs/nullifier_migration.md
    - Mining Pool Setup: docs/mining_pool_setup.md
  - Foundation: foundation.md

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/YcashFoundation'
    - type: 'reddit'
      link: 'https://reddit.com/r/ycashtalk'
    - type: 'github'
      link: 'https://github.com/YcashFoundation/ycash/'
    - type: 'telegram'
      link: "https://google.com"
